name: Create Surefire Report

on:
   schedule:
    - cron: '0 0 * * *'

jobs:
  report:
    runs-on: ubuntu-latest
    env:
      MVN: ./mvnw --show-version --batch-mode
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        id: setup-jdk
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Run Tests
        id: run-tests
        run: $MVN --fail-never -P all-tests test -Dsurefire.failIfNoSpecifiedTests=false
      - name: Site
        id: site
        run: $MVN -P all-tests site:site -DskipTests -Daggregate=true -Dsurefire.failIfNoSpecifiedTests=false
      - name: Publish
        id: publish
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          branch: gh-pages
          folder: ./target/site
          clean: true
