name: Test Single Module

on:
  workflow_dispatch:
    inputs:
      hal-image:
        type: choice
        required: true
        default: quay.io/halconsole/hal
        description: 'The HAL image name'
        options:
          - quay.io/halconsole/hal
          - quay.io/halconsole/hal-development
      module:
        description: 'The module (directory name) to test'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MVN: ./mvnw --show-version --batch-mode
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5
      - name: Set up JDK
        id: setup-jdk
        uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Install
        id: install
        run: $MVN install
      - name: Run Tests
        id: run-tests
        run: $MVN --projects ${{ github.event.inputs.module }} --also-make -P all-tests test -Dhal.image=${{ github.event.inputs.hal-image }} -Dsurefire.failIfNoSpecifiedTests=false
