name: Verify Codebase

on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      MVN: ./mvnw --show-version --batch-mode
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5
      - name: Set up JDK
        id: setup-jdk
        uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Verify
        id: verify
        run: $MVN -P all-tests -DskipTests verify
